// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type Word struct {
	ID           int32
	Word         string
	Partofspeech sql.NullString
}
